### ISSUE TITLE
[cf]: Improve UserData script

### ISSUE THREAD

**Issue by adriagalin** [cycloid-community-catalog/stack-external-worker#29]
Following Hugo's comments on PR #25:

- Can we use a file as parameter or something like this? Might make it easier to read and easier to use parameters for various variables. [link](https://github.com/cycloid-community-catalog/stack-external-worker/pull/25/files/58027e0e4b4de1597bd61852861e321d8034b2dd#r296226076)

- Do we really want to erase the file instead of adding / setting this config? [link](https://github.com/cycloid-community-catalog/stack-external-worker/pull/25/files/58027e0e4b4de1597bd61852861e321d8034b2dd#r296225537)

- Is there eventually something better to check than sleep 60? [link](https://github.com/cycloid-community-catalog/stack-external-worker/pull/25/files/58027e0e4b4de1597bd61852861e321d8034b2dd#r296225813)

**Comment by gaelL** [comment]
Closing this issue, there is still room for improvements but today's version now use a common script for Aws/Gcp ans Azure.
